server:
  port: 8080

spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    # 开发禁用缓存
    cache: false

  #跳转页面路径
  mvc:
    view:
      prefix: /webapp
      suffix: .html

  #上传视频的大小限制
  http:
    multipart:
      max-file-size: -1
      max-request-size: -1
      location: /var/tmp

  #redis配置
  redis:
    host: 101.37.252.177
#    host: 47.97.125.222
    port: 63000
    password: heyuan123456.
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间
        max-wait: 60000
        #最大空闲连接
        max-idle: 8
        #最小空闲连接
        min-idle: 0
    timeout: 0
    database: 0

  pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params:

#druid相关配置
  druid:
    username: root
    password: Ab323232
    #基本属性
    url: jdbc:mysql://101.37.252.177:33060/yuyue?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    url: jdbc:mysql://47.97.125.222:33060/yuyue?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    #配置初始化大小/最小/最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #获取连接等待超时时间
    maxWait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    #一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #监控统计拦截的filters
    filters: stat
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    #pool-prepared-statements: false

# MyBatis
mybatis:
  typeAliasesPackage: com.yuyue.boss.*.domain
  mapperLocations: classpath:/mappers/*.xml
  configLocation: classpath:/mybatis-config.xml

# spring-boot默认打印输出info级别以上的，可在此处修改输出级别
logging:
  config: classpath:logback-spring.xml
  #打印sql#
  level:
    com.yuyue.app.api.mapper: debug
    #root: info

fdfs:
  so-timeout: 60000 #上传的超时时间
  connect-timeout: 60000 #连接超时时间
  tracker-list: 101.37.252.177:22122
#  tracker-list: 47.97.125.222:22122
  pool:
    jmx-enabled: false

#极光推送
jpush:
  #ced8805d8d62e42cca2f5bda
  appKey: c9b42236019679709d0d0ebe
  #b8dae5591819e15fc3543cb6
  masterSecret: ba4e6c2302185825bbc50cb0
  apnsProduction: false   # 是否生成环境，true表示生成环境


#PageHelper的配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
